generator_type: tf

# controller_frequency: 20
controller_frequency: 10

controller_no_setpoint_timeout: 2

# tf_prefix: alpha_rise

cg_link: cg_link

odometry_source: /odometry/filtered/local

enabled: false

control_modes:
  idle: false

  flight:
    surge:    {p: 100.0,   i: 30.0,   d: 1.0,   pid_max: 300.0, pid_min: -300.0}
    yaw:      {p: 40.0,   i: 1.0,   d: 5.0,  pid_max: 150.0, pid_min: -150.0}

##
# THRUSTERS
##
thruster_ids:
  - port
  - starboard

control_tf:
  port: port_thruster_link
  starboard: starboard_thruster_link


thruster_command_topics:
  port: port_thruster
  starboard: starboard_thruster


thruster_force_topics:
  port: control/force/port_thruster
  starboard: control/force/starboard_thruster



##
# Polynomials for each thruster.
#
# Quadratic Programming Optimization computes the thrust
# required. We need to turn that number into thruster command.
# Setpoint commands in this system defined between -1 and 1.
#
# y axis of the polynomial , f(x) = y, should be in Newton.
#
# Take the polynomial
# f(x) = a_n x^n + a_(n-1) x^(n-1) + ... + a_1 x + a_0
#
# Array would hold the lower degrees in lower indexes. Shown below:
# [a_0, a_1, ... ,a_(n-1), a(n)]
#   f(x) = a5*x^5 + a4*x^4 + a3*x^3 + a2*x^2 + a1*x + a0
thruster_polynomials:
  # T = 0.0014*RPM^2 = 1400*command^2 [-1, 1]
  # port:        [0.0, 0.0, 1400.0]
  # starboard:     [0.0, 0.0, 1400.0]
  # port:        [0.0, 200.0]
  # starboard:     [0.0, 200.0]
  
  # f(x) = 1015.8 *x^3 + 0*x^2 + 439.65*x
  port:      [0.0, 439.65, 0.0, 1015.8]
  starboard: [0.0, 439.65, 0.0, 1015.8]
  

## Force limits
## T200 limit is +-25 N beyond that will cause nan solution in QP
thruster_limits:
  port:
    max: 150
    min: -150
  starboard:
    max: 150
    min: -150