
voltage:
    # brief: device address
    address: "0x69"
    #
    gain: 1
    # 
    bitrate: 18
    # 
    mode: 1
    #
    channel: 2

current:
    # brief: device address
    address: "0x69"
    #
    gain: 1
    # 
    bitrate: 18
    # 
    mode: 1
    #
    channel: 1

system:
    #
    rate: 5
    # 
    voltage_ratio: 0.090082
    # 
    voltage_warn: 21.0        
    #
    current_ratio: 0.092147
    #
    current_offset: 2.5
    #
    current_scale: 0.066