Serial:
  port: /dev/torqeedo_port
  baud: 19200
  parity: 0
  databits: 8
  stopbits: 1
  timeout: 1000

Motor:
  # note: Wiring Pi pin number
  pin: 13

System:
  safety_timeout: 2
  # Brief: default value is 0.4 tested in salt pond
  scale: 0.4

ROS:
  frame_id: torqeedo_port