Serial:
  port: /dev/torqeedo_starboard
  baud: 19200
  parity: 0
  databits: 8
  stopbits: 1
  timeout: 1000

Motor:
  # note: Wiring Pi pin number
  pin: 27

System:
  safety_timeout: 2
  # Brief: default value for field (e.g., salt pond) is 0.4
  # Brief: default value for test is 0.1
  scale: 0.1

ROS:
  frame_id: torqeedo_starboard