# /wamv_rise/airmar_ws:
/**:
  ros__parameters:
    # The usb device for unicore gps
    # device: /dev/ttyUSB5
    device: /dev/airmar
    baudrate: 4800

    # True: use the gps timestamp, False: use IO time when gps message arrived
    use_gnss_time: False