# /wamv_rise/world_odom_transform_node:
/**:
  ros__parameters:
    acceptable_var: 5.0
    m_gps_wait_time: 30.0

    ## CACS
    datum_latitude: 41.4904292
    datum_longitude: -71.4230804

    ## salty pond
    # datum_latitude: 41.4272412
    # datum_longitude: -71.4964559

    position_accuracy: 3.0
    mag_declination_auto: false
    use_depth_for_tf: true
    datum_manual_start: false

    manual_position_covariance: 1.0