/wamv_rise/mvp_c2_traffic_control:
  ros__parameters:

    max_frame_size: 200  #maximum size per transmission packet
    tx_interval: 1.0

    tdma_enable: False

    tdma:
      slot_id: 0
      role: "master"
      slot_duration: 10.0
      num_slots: 3
      slot_guard_time_ms: 100
      sync_slot_interval: 5
      sync_msg_repeat_num: 5
      
    # --- Buffer Global Settings ---
    dynamic_buffer:
      max_total_size: 150 # how many dccl message entries will be stored
      overflow_remove_by_time: False
      dccl_intake_message_list: ["Joy", "SetPowerPort", "SetController", "SetHelm", "SetWpt", "RosLaunch"]

    # --- Message Specific Rules ---
    # Higher means priority
    message_rules:
      RosLaunch:
        priority: 10
        ttl_seconds: 100

      SetPowerPort:
        priority: 9
        ttl_seconds: 100

      SetController:
        priority: 8
        ttl_seconds: 100

      SetHelm:
        priority: 7
        ttl_seconds: 100

      SetWpt:
        priority: 6
        ttl_seconds: 100

      Joy:
        priority: 5
        ttl_seconds: 5