###########################################################
## vehicle side stuff
###########################################################
/wamv_rise/mvp_c2_reporter:
  ros__parameters:
    dccl_tx_interval: 1.0
    dccl_rx_interval: 0.2
    helm_state_list: ['start', 'kill', 'teleop', 'survey', 'manual_teleop'] #this has to match the helm
    launch_packages: ['wamv_rise_bringup', 'wamv_rise_bringup', 'wamv_rise_bringup', 'wamv_rise_bringup',  'wamv_rise_bringup']
    launch_files: ['bringup_pi_utilities', 'bringup_pi_thruster', bringup_pi_payload, 'bringup_pi_localization', 'bringup_pi_mvp']
    gpio_devices: [underwater_payload, jetson_board, norbit]  # this needs to match the gpio manager yaml
    local_id: 4
    remote_id: 3

/wamv_rise/reporter_c2_serial_comm:
  ros__parameters:
    # port: /dev/ttyUSB4
    port: /dev/vehicle_rf
    baudrate: 115200
    send_chunks_flag: True

# /wamv_rise/reporter_c2_udp_comm:
#   ros__parameters:
#     type: client
#     server_ip: 192.168.2.8
#     server_port: 5000
#     client_ip: 192.168.2.55
#     client_port: 6000
#     dccl_tx_interval: 1.0

###########################################################
## topside stuff
###########################################################

/wamv_rise/mvp_c2_commander:
  ros__parameters:
    dccl_tx_interval: 1.0
    dccl_rx_interval: 0.1
    helm_state_list: ['start', 'kill', 'teleop', 'survey', 'manual_teleop'] #this has to match the helm
    launch_packages: ['wamv_rise_bringup', 'wamv_rise_bringup', 'wamv_rise_bringup', 'wamv_rise_bringup',  'wamv_rise_bringup']
    launch_files: ['bringup_pi_utilities', 'bringup_pi_thruster', bringup_pi_payload, 'bringup_pi_localization', 'bringup_pi_mvp']
    gpio_devices: [underwater_payload, jetson_board, norbit]  # this needs to match the gpio manager yaml
    local_id: 3
    remote_id: 4

/wamv_rise/commander_c2_serial_comm:
  ros__parameters:
    # port: /dev/ttyUSB0
    port: /dev/topside_rf
    baudrate: 115200

# /wamv_rise/commander_c2_udp_comm:
#   ros__parameters:
#     type: server
#     server_ip: 192.168.2.8
#     server_port: 5000
#     client_ip: 192.168.2.55
#     client_port: 6000