/**:
  ros__parameters:

    # control serial: send motor cmd (/dev/ttyUSB#)
    control_device: /dev/roboclaw_control
    control_baudrate: 115200

    # read serial: get info from motor (/dev/ttyACM0)
    read_device: /dev/roboclaw_info
    read_baudrate: 115200
