/wamv_rise/imu_driver_node:
    ros__parameters:
      roll_offset: 3.1415926
      pitch_offset: 0.0
      yaw_offset: 1.5707
      roll_reverse: 1.0
      pitch_reverse: -1.0
      yaw_reverse: -1.0


/wamv_rise/dvl_driver_node:
    ros__parameters:
      dvl_in: /wamv_rise/dvl/stonefish/raw
      dvl_out: /wamv_rise/dvl/twist
      dvl_alt_out: /wamv_rise/dvl/altitude