# /wamv_rise/torqeedo_port:
/**:
  ros__parameters:

    Serial:
      port: /dev/torqeedo_port
      baud: 19200
      parity: 0
      databits: 8
      stopbits: 1
      timeout: 1000

    Motor:
      # note: Wiring Pi pin number
      pin: 23

    System:
      safety_timeout: 2
      scale: 0.1

    ROS:
      frame_id: wamv_rise/torqeedo_port