# /wamv_rise/torqeedo_port:
/**:
  ros__parameters:

    Serial:
      port: /dev/torqeedo_port
      baud: 19200
      parity: 0
      databits: 8
      stopbits: 1
      timeout: 1000

    Motor:
      # note: Wiring Pi pin number
      pin: 27

    System:
      safety_timeout: 2
      # scale: 0.2
      scale: 0.5

    ROS:
      frame_id: wamv_rise/torqeedo_port

      # brief: the HELM state that let thruster listen to controller commands
      #        the name should be same as the state defined in 'finite_state_machine' of helm.yaml
      controller_state_names: [teleop, survey]

      # brief: the HELM state that let thruster listen to joy commands
      #        the name should be same as the state defined in 'finite_state_machine' of helm.yaml      
      manual_state_names: [manual_teleop]

      # brief: the joy axes (index) used to control the thruster speed
      # No.2 of the axis for port: index = 1
      # No.4 of the axis for stbd, index = 3
      joy_axes: 1

      # brief: the joy button(index) used to enable the control from joy 
      joy_buttons: 4